### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cxw42** [bernardelli/Bilateral-Filter-GPU#5]
Thank you for posting this project, which looks very useful!  I also appreciate the slides (https://www12.cs.fau.de/edu/map/talks/bgf_tesla.pdf).  What is the license for this code?  I cannot find a license file, or any license or copyright statements in the source files.  Thank you!

Sincerely,
Chris White

**Comment by bernardelli** [comment]
I just updated the license!

As this was my (and @gerry3309's) first ever CUDA project, the implementation is not the best it can be. Use at your own risk!

**Comment by cxw42** [comment]
:) Much appreciated!
